# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
