# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-17 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copapp', '0004_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='friend_phone_number',
        ),
    ]
